version: '3.1'
services:
    mongo: 
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'
        
    app:
        container_name: fastify-app
        restart: always
        build: .
        ports: 
            - '3000:3000'
        external_links:
                - mongo